spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.jiadong: info
  file:
    name: log/blog-pro.log
server:
  port: 8081
